import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './UI/components/Header/Header'
import Provider from './UI/components/Provider/Provider'




const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'next-project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <main>
            <Header />
            <div className='relative'>{children}</div>
          </main>
        </body>
      </Provider>
    </html>
  )
}
